run.DEB.sim <- function(datelay, nyears){
  leapyears <- seq(1900,2024,4)
  startyear <- year(datelay)
  endyear <- startyear+nyears -1 
  yearvec <- c(startyear:endyear)
  simdays <- sum(ifelse(yearvec %in% leapyears,366,365))
  start <- which(format(micro$dates, "%Y-%m-%d") == format(datelay, "%Y-%m-%d"))[1]
  
  while(micro$metout[start,2] != 0){
    start <- start -1
  }
  finish <- min(start + 24 * simdays - 1, micro$ndays*24)
  start2 <- which(format(micro$dates2, "%Y-%m-%d") == format(datelay, "%Y-%m-%d"))[1]
  finish2 <- min(start2 + simdays - 1, micro$ndays)
  
  minshades <- matrix(rep(0, length(start2:finish2)))
  maxshades <- matrix(rep(90, length(start2:finish2)))
  startday = 1
  
  # Ecotherm mod  
  ecto <- ectotherm(write_input = 0,
                    nyears = nyears,
                    write_csv = 0,
                    metout = micro$metout[start:finish,],
                    soil = micro$soil[start:finish,],
                    soilpot = micro$soilpot[start:finish,],
                    soilmoist = micro$soilmoist[start:finish,],
                    humid = micro$humid[start:finish,],
                    shadmet = micro$shadmet[start:finish,],
                    shadsoil = micro$shadsoil[start:finish,],
                    shadpot = micro$shadpot[start:finish,],
                    shadmoist = micro$shadmoist[start:finish,],
                    shadhumid = micro$shadhumid[start:finish,],
                    rainfall = micro$RAINFALL[start2:finish2],
                    minshades = minshades,
                    maxshades = maxshades,
                    DEB = rundeb,
                    intmethod = 1,
                    clutchsize = clutchsize,
                    #clutch_ab = clutch_ab,
                    #minclutch = minclutch,
                    #maxclutch = maxclutch,
                    shape = shape,
                    #arrhenius = arrhenius,
                    alpha_max = alpha_max,
                    alpha_min = alpha_min,
                    T_F_min = T_F_min,
                    T_F_max = T_F_max,
                    T_B_min = T_B_min,
                    T_RB_min = T_RB_min,
                    T_pref = T_pref,
                    CT_max = CT_max,
                    CT_min = CT_min,
                    diurn = diurn,
                    nocturn = nocturn,
                    crepus = crepus,
                    shade_seek = shade_seek,
                    burrow = burrow,
                    climb = climb,
                    shdburrow = shdburrow,
                    mindepth = mindepth,
                    maxdepth = maxdepth,
                    pct_H_P = pct_H_P,
                    pct_wet = pct_wet,
                    pct_eyes = pct_eyes,
                    pct_H_X = pct_H_X,
                    z = z * z_mult,
                    del_M = del.M,
                    p_Xm = F_m_ref * z_mult^3 / 24,
                    kap_X = kap.X,
                    v = v / 24,
                    kap = kap,
                    p_M = p.M / 24,
                    E_G = E.G,
                    E_0 = E.0*z.mult^4, 
                    kap_R = kap.R,
                    k_J = k.J / 24,
                    E_Hb = E.Hb * z_mult^3,
                    E_Hp = E.Hp * z_mult^3,
                    h_a = h.a  * z_mult / 10 / (24 ^ 2),
                    s_G = s.G,
                    T_REF = T.ref,
                    T_A = T.A,
                    T_AL = T.AL,
                    T_AH = T.AH,
                    T_L = T.L + 6,
                    T_H = T.H,
                    f = f,
                    E_sm = E_sm * z_mult^3,
                    K = K,
                    X = X,
                    d_V = d.V,
                    d_E = d.E,
                    d_Egg = d_Egg,
                    soilnode = soilnode,
                    mu_X = mu.X,
                    mu_E = mu.E,
                    mu_V = mu.V,
                    mu_P = mu.P,
                    kap_X_P = kap.P,
                    n_X = c(n.CX, n.HX, n.OX, n.NX), 
                    n_E = c(n.CE, n.HE, n.OE, n.NE), 
                    n_V = c(n.CV, n.HV, n.OV, n.NV), 
                    n_P = c(n.CP, n.HP, n.OP, n.NP), 
                    n_M_nitro = c(n.CN, n.HN, n.ON, n.NN),
                    L_b = L.b,
                    V_init = V_init,
                    E_init = E_init,
                    E_H_init = E_H_init,
                    stage = stage,
                    reset = reset,
                    metab_mode = metab_mode,
                    viviparous = viviparous,
                    photostart = photostart,
                    photofinish = photofinish,
                    batch = batch,
                    startday = startday,
                    stages = stages,
                    #S_instar = S_instar,
                    raindrink = raindrink,
                    aestivate = aestivate,
                    aestdepth = aestdepth,
                    depress = depress,
                    pct_H_R = pct_H_R,
                    starvemode = 1,
                    daylengthstart = 10.50,
                    daylengthfinish = 13.44)
  return(list(ecto = ecto, start = start, finish = finish))
}